---
# This Playbook will setup a workstation from scratch

- hosts: local
  vars:
    username: smeier ## todo use current user as default
    full_username: Sandy Meier
    email_address: smeier@tapnic.com
    home_dir: "/home/{{username}}"
    #home_dir: "{{ ansible_env.HOME }}" can't be used because its "root" in sudo mode
    home_bin: "{{home_dir}}/bin"
  sudo: yes
  roles:
  - role: common
  - role: java
  - role: android
#  - role: nodejs
#  - role: ruby
  - role: usenet
#  - {role: docker, sudo: no}
  - role: wine





