---
# This Playbook will setup a workstation from scratch

- hosts: local
  vars:
    username: smeier ## todo use current user as default
    full_username: Sandy Meier
    email_address: smeier@tapnic.com
    home_dir: "/home/{{username}}"
    #home_dir: "{{ ansible_env.HOME }}" can't be used because its "root" in sudo mode
    home_bin: "{{home_dir}}/bin"
    # used for backup role
    ccollect_config: "{{home_dir}}/.config/ccollect"
    home_backup_dir: "/media/smeier/Backup/workstation"
  sudo: yes
  roles:
  - role: common
  - {role: backup, sudo: no}
  - role: eos
  - role: java
  - role: usenet
  - {role: docker, sudo: no}





