---
- name: create backup dir
  file: path={{home_backup_dir}} state=directory mode=0755
  ignore_errors: yes

- name: copy ccollect to user bin directory
  copy: src=bin/ccollect dest={{home_bin}}/ mode=u+rwx

- name: copy ccollect_wrapper to user bin directory
  template: src=ccollect_wrapper dest={{home_bin}}/ mode=u+rwx

- name: copy ccollect interval files
  copy: src={{item}} dest={{ccollect_config}}/defaults/intervals/
  with_items:
      - daily
      - weekly
      - monthly

- name: copy ccollect config for "home"
  copy: src={{item}} dest={{ccollect_config}}/sources/home/
  with_items:
      - home/exclude
      - home/delete_incomplete # used as marker
      - home/summary # used as marker

- name: copy ccollect config for "home"
  template: src={{item}} dest={{ccollect_config}}/sources/home/
  with_items:
      - home/source
      - home/destination

- name: set cron job for daily backup, every day 20 a clock
  cron: name="backup home daily" hour="20" minute="0" job="{{home_bin}}/ccollect_wrapper daily home"
- name: set cron job for weekly backup, every sunday at 21 a clock
  cron: name="backup home weekly" hour="21" minute="0" weekday="0" job="{{home_bin}}/ccollect_wrapper weekly home"
- name: set cron job for monthly backup, every 15. at 22 a clock
  cron: name="backup home monthly" hour="22" minute="0" day="15" job="{{home_bin}}/ccollect_wrapper monthly home"