#!/bin/bash

export CCOLLECT_CONF={{ccollect_config}}/
export DISPLAY=:0.0
START=$(date +"%s")
RET=`{{home_bin}}/ccollect $1 $2`
END=$(date +"%s")

DIFF=$(($END-$START))
DURATION="$(($DIFF / 60))m:$(($DIFF % 60))s"

if [[ $RET =~ " Error: " ]]  || [[ $RET =~ "rsync exited non-zero" ]];
then
    /usr/bin/notify-send --expire-time=1000000 "Error in $1 backup:
    $RET"  --urgency=critical
else
	/usr/bin/notify-send --expire-time=10000 "Backup created
Duration: $DURATION"
fi