---
# This playbook contains common base packages.

- name: Linux | Update cache
  apt: update_cache=yes cache_valid_time=3600

- name: Package | Install lists packages
  apt: pkg={{ item }} state=installed
  with_items:
    - bash-completion
    - vim
    - git
    - curl
    - wget
    - htop
    - unzip
    - tar
    - gzip
    - bzip2
    - thunderbird 
    - enigmail 
    - xul-ext-gdata-provider 
    - xul-ext-lightning
    - unrar 
    - rar
    - ksysguard
#    - kdegraphics-strigi-plugins # dolphin pdf previews
    - dstat 
    - fslint 
    - gparted
    - gsfonts-x11
    - baobab
    - firefox
    - tree
    - xsel
    - xclip
    - libreoffice
    - nautilus
    - mc
    - ncdu
    - lnav # http://lnav.org/
    - transmission
    - filezilla
    - nautilus-dropbox
    - vagrant
    - pidgin
    - colorname # its always good to know the names
    - network-manager-openvpn
    - python-pip
    - aptitude
    - nfoview
    - diodon # clipboard manager

