---
# This playbook contains common base packages.

- name: Linux | Update cache
  apt: update_cache=yes cache_valid_time=3600

- name: Package | Install lists packages
  apt: pkg={{ item }} state=installed
  with_items:
    - bash-completion
    - vim
    - git
    - curl
    - wget
    - htop
    - unzip
    - tar
    - gzip
    - bzip2
    - thunderbird 
    - enigmail 
    - xul-ext-gdata-provider 
    - xul-ext-lightning
    - unrar 
    - rar
    - konsole 
    - ksysguard 
    - dstat 
    - fslint 
    - gparted 
    - flashplugin-installer 
    - gsfonts-x11
    - baobab
    - firefox
    - tree
    - xsel
    - xclip
    - comix
    - gimp
    - krita
    - libreoffice
    - nautilus
    - dolphin
    - mc
    - ncdu
    - lnav # http://lnav.org/
    - transmission
    - filezilla
    - nautilus-dropbox
    - vagrant
    - pidgin
    - lib32stdc++6 # android adb
    - lib32z1 # android adb
    - libgl1-mesa-glx-lts-utopic:i386 # steam
    - k3b
    - calibre
    - colorname # its always good to know the names
    - mysql-server
    - network-manager-openvpn
    - python-pip
    - aptitude


- name: ensure sublime text repo available
  apt_repository: repo='ppa:webupd8team/sublime-text-3'

- name: Package | Install sublime text
  apt: pkg={{ item }} state=installed
  with_items:
    - sublime-text-installer

- name: ensure Trusty Media (https://launchpad.net/~mc3man/+archive/ubuntu/trusty-media/) repo available
  apt_repository: repo='ppa:mc3man/trusty-media'

- name: Package | Install vlc
  apt: pkg=vlc state=installed update_cache=yes cache_valid_time=3600