---

- name: copy screenfetch
  copy: src=screenfetch-dev dest=/home/{{username}}/bin/ mode=u+rwx owner={{username}}
- name: copy email signature file
  copy: src=signature dest=/home/{{username}}/.signature owner={{username}}
- name: copy vim configuration
  copy: src=vimrc dest=/home/{{username}}/.vimrc owner={{username}}
- name: link vim plugins folder
  file: src=/home/{{username}}/programs/.vim dest=/home/{{username}}/.vim state=link

- name: create gitconfig
  template: src=gitconfig dest=/home/{{username}}/.gitconfig owner={{username}}
