- name: Install diodon clipboard manager
  apt: pkg={{ item }} state=installed
  with_items:
    - diodon

- name: add repo for sysmonitor indicator - https://github.com/fossfreedom/indicator-sysmonitor
  apt_repository: repo='ppa:fossfreedom/indicator-sysmonitor'

- name: Package | Install sysmonitor indicator
  apt: pkg={{ item }} state=installed
  with_items:
    - indicator-sysmonitor

- name: copy some indicators to autostart
  copy: src={{item}} dest=/home/{{username}}/.config/autostart/ owner={{username}}
  with_items:
    - indicator-sysmonitor.desktop
