---
- name: ensure Trusty Media (https://launchpad.net/~mc3man/+archive/ubuntu/trusty-media/) repo available
  apt_repository: repo='ppa:mc3man/trusty-media'

- name: Package | Install vlc
  apt: pkg=vlc state=installed update_cache=yes cache_valid_time=3600

- name: Package | Install lists packages
  apt: pkg={{ item }} state=installed
  with_items:
    - flashplugin-installer
    - comix
    - gimp
    - krita
    - calibre
    - k3b
