---
#- name: ensure Trusty Media (https://launchpad.net/~mc3man/+archive/ubuntu/trusty-media/) repo available
#  apt_repository: repo='ppa:mc3man/trusty-media'

#- name: Package | Install vlc
#  apt: pkg={{ item }} state=installed update_cache=yes cache_valid_time=3600
#  with_items:
#    - vlc
#    - vlc-plugin-libde265 # H.265/HEVC support

- name: Package | Install lists packages
  apt: pkg={{ item }} state=installed
  with_items:
    - flashplugin-installer
    - comix
    - gimp
    - krita
    - calibre
    - vlc
    - ubuntu-restricted-extras # mp3, mp4
      #    - k3b
