---
# This playbook contains common base packages.

- name: Linux | Update cache
  apt: update_cache=yes cache_valid_time=3600

- name: Package | Install lists packages
  apt: pkg={{ item }} state=installed
  with_items:
    - bash-completion
    - vim
    - git
    - curl
    - wget
    - htop
    - unzip
    - tar
    - gzip
    - bzip2
    - pwgen
    - thunderbird 
    - enigmail 
    - xul-ext-gdata-provider 
    - xul-ext-lightning 
    - vlc 
    - unrar 
    - rar
    - konsole 
    - ksysguard 
    - dstat 
    - fslint 
    - gparted 
    - flashplugin-installer 
    - gsfonts-x11
    - baobab
    - firefox
    - mc 
    - tree
    - xsel
    - xclip
    - comix
    - gimp
    - krita
    - gnupg2
    - keepass2
    - libreoffice
    - nautilus
    - dolphin
    - transmission
    - nautilus-dropbox
    - virtualbox
    - virtualbox-dkms
    - vagrant
    - pidgin
    - lib32stdc++6 # android adb
    - lib32z1 # android adb
    - libgl1-mesa-glx-lts-utopic:i386 # steam
    - k3b


- name: ensure sublime text repo available
  apt_repository: repo='ppa:webupd8team/sublime-text-3'
- name: Package | Install sublime text
  apt: pkg={{ item }} state=installed
  with_items:
    - sublime-text-installer
