- name: Package | Install security/crypto packages
  apt: pkg={{ item }} state=installed
  with_items:
    - gnupg2
    - keepass2
    - pwgen

- name: ensure  https://launchpad.net/~keepassx/+archive/ubuntu/daily repo available
  apt_repository: repo='ppa:keepassx/daily'

- name: Package | Install keepassx
  apt: pkg=keepassx state=installed update_cache=yes cache_valid_time=3600
